network: resnet50
data_shape: 512
batch_size: 8
gpus: '0'
resume: False
start_epoch: 0
epoch: 400
train_workers: 12
eval_workers: 4
height: 512
width: 512
lr: 0.001
lr_mode: step
lr_decay: 0.1
wd: 0.00001
momentum: 0.9
lr_decay_period: 0
lr_decay_epoch: 200, 340
warmup_lr: 0.0
warmup_epochs: 1
log_interval: 100
save_prefix: model/
seed: 233
log_path: output
num_sample: 9998
num_val: 128
train_data_path: [/home/zhao/work/ocr/OCR/train_data/det_0302_0326_0327_0410/imgs]
val_data_path: [/home/zhao/work/ocr/OCR/train_data/20180302/detection/eval_prd]
min_text_size: 8
min_crop_side_ratio: 0.4
max_iter: 50
background_ratio: 0.375
geometry: RBOX
R: 0.3
vis: False
grad_scale: 128.0
